defaults:
  - loss: cross_entropy.yaml
  - metric: accuracy.yaml
  - optimizer: adam.yaml
  - lr_scheduler: reduce_lr_on_plateau.yaml

_target_: cctest.models.base_trainer_module.TrainingModule

# set `-1` to train on all GPUs in a node,
# '>0' to train on specific num of GPUs in a node,
# `0` to train on CPU only,
gpus: -1

epochs: 5
#weights_summary: null
#progress_bar_refresh_rate: 5
#resume_from_checkpoint: null
