defaults:
  - loss: cross_entropy.yaml
  - metric: accuracy.yaml
  - optimizer: adam.yaml
  - lr_scheduler: reduce_lr_on_plateau.yaml

_target_: cctest.model.base_model_trainer.TrainingModule

# set `-1` to train on all GPUs in a node,
# '>0' to train on specific num of GPUs in a node,
# `0` to train on CPU only,
gpus: -1

epochs: 10
validation_freq: 1
