defaults:
  - loss: bce_dice.yaml
  - metric: many_matrices.yaml
  - optimizer: adam.yaml
  - lr_scheduler: reduce_lr_on_plateau.yaml

_target_: cctest.model.base_model_trainer.TrainingModule

# set `-1` to train on all GPUs in a node,
# '>0' to train on specific num of GPUs in a node,
# `0` to train on CPU only,
gpus: -1
epochs: 50
validation_freq: 5

optimizer:
  learning_rate: 0.003
