repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.0
    hooks:
      - id: add-trailing-comma

  # python code formatting
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7 # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
        args: [--max-line-length, '120', --in-place]

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
      - id: isort

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [yaml]
        args: [--single-quote]

  # python code analysis
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ['--config=setup.cfg']
        language: python
        types: [python]
