# @package _global_

# run in debug mode with:
# `python run.py mode=debug`

defaults:
  - override /trainer: debug.yaml

debug_mode: True

# name of the run, accessed by loggers
name: run_${current_time}

hydra:
  # sets level of all command line loggers to 'DEBUG'
  verbose: [__main__, hydra, cctest]

  # https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  # sets level of only chosen command line loggers to 'DEBUG'
  # verbose: [src.train, src.utils.utils]

  # sets output paths for all file logs to 'logs/debug/'
  run:
    dir: logs/debug/${name}
  sweep:
    dir: logs/debug/multirun/${name}
    subdir: ${hydra.job.num}
  output_subdir: "hydra_training"

# disable rich config printing, since it will be already printed by hydra when `verbose: True`
print_config: False
