# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

experiment_mode: True

# forces custom naming of the experiment
name: ???

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: logs/experiments/${name}/${current_time}
  sweep:
    dir: logs/experiments/multirun/${name}/${current_time}
    subdir: ${hydra.job.num}
  output_subdir: "hydra_training"
