# https://wandb.ai/quickstart/keras

wandb_init:
  user: ${oc.env:WANDB_USER}
  project: CC-DL-template-example
  name: ${name}
  job_type: training

wandb:
  _target_: wandb.keras.WandbCallback
  monitor: val_loss
  mode: min
  save_model: False
  save_graph: True
  log_weights: True
