# https://wandb.ai/quickstart/keras

wandb_init:
  user: null
  project: CC_example_template
  name: ${name}

wandb:
  _target_: wandb.keras.WandbCallback
  monitor: val_loss
  mode: min
  save_model: False
  save_graph: True
  log_weights: True
