# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default_seg.yaml
  - model: oxfordpet_model_unet.yaml
  - datamodule: oxfordpet_datamodule.yaml
  - callback: default.yaml
  - logger: many_loggers.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)

  # every run/experiment is sacred (think before doing an experiment), everything else is debugging
  - mode: debug.yaml

  - experiment: null
  - hparams_search: null

  - override trainer: default_seg.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

current_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# pretty print history after the run using Rich library
print_history: True

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in tensorflow, numpy and python.random
seed: null

# name of the run, accessed by loggers
name: null
