defaults:
  - data_aug: medium_aug.yaml

_target_: cctest.datamodule.mnist_datamodule.MNISTDataset

data_dir: ${data_dir} # data_dir is specified in config.yaml
data_training_list: "training_data.txt"
data_val_list: "validation_data.txt"
data_test_list: "test_data.txt"
batch_size: 64
