defaults:
  - data_aug: oxfordpet_medium_aug.yaml

_target_: {{cookiecutter.module_name}}.datamodule.oxfordpet_datamodule.OxfordPetDataset

data_dir: ${data_dir} # data_dir is specified in config.yaml
train_list: "OxfordPet_training_data.txt"
val_list: "OxfordPet_validation_data.txt"
test_list: "OxfordPet_test_data.txt"
batch_size: 64
